languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "EN"

title = "Chandra's Ckloud Journal"

[author]
  name = "Chandra Kanth"
  links = [
    { linkedin = "https://linkedin.com/in/YOUR-LINKEDIN-ID" },
    { github = "https://github.com/ckanth15" },
  ]
