[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [main.params]
    icon = "home"

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30
