colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  cardView = true
  cardViewScreenWidth = false
  showAuthor = true
  homepageImage = ""
  showTitle = false

[article]
  showHero = true
  heroStyle = "thumbAndBackground"
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showPagination = true

[list]
  showCards = true
  cardView = true
  groupByYear = true

[taxonomy]
  showTermCount = true
